"""phase2 suppliers pricing_rules

Revision ID: 47f82460bc0a
Revises: 495d3911ae53
Create Date: 2026-05-17 11:06:27.051704
"""
from alembic import op
import sqlalchemy as sa


revision = '47f82460bc0a'
down_revision = '495d3911ae53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('price_tier', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('markup_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('markup_floor', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('price_floor', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rounding', sa.String(length=10), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('connector', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###

    # --- Seed phase 2 : règle de marge par défaut 10 % + fournisseur ---
    op.execute(
        """
        INSERT INTO pricing_rules
            (id, markup_percent, rounding, priority, is_active, created_at)
        VALUES
            (gen_random_uuid(), 10.00, 'psych', 0, true, now())
        """
    )
    op.execute(
        """
        INSERT INTO suppliers (id, name, connector, is_active, created_at)
        VALUES (gen_random_uuid(), 'Maxityre', 'maxityre', true, now())
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppliers')
    op.drop_table('pricing_rules')
    # ### end Alembic commands ###
